import type { EntityPageContent } from "../types";

/** Daily intelligence pages — template content; production will be generated by cron. */
export const DAILY_PAGES: Record<string, EntityPageContent & { date: string }> = {
  "biggest-movers": {
    slug: "biggest-movers",
    date: new Date().toISOString().slice(0, 10),
    title: "Today's Biggest Movers",
    metaDescription: "Daily recap of the biggest stock movers with AI context on MotiveFX.",
    kicker: "Daily intelligence",
    lead: "Every trading day MotiveFX publishes the largest price and volume movers with Motive Signal context and Why It Matters summaries.",
    sections: [
      { heading: "How this page is built", paragraphs: ["Automated scanners rank RVOL and percent change; AI layer adds narrative and sector linkage. Updated intraday."] },
    ],
    faqs: [],
    relatedLinks: [{ label: "Stocks module", href: "/markets/stocks" }, { label: "Institutional buying today", href: "/daily/institutional-buying" }],
  },
  "institutional-buying": {
    slug: "institutional-buying",
    date: new Date().toISOString().slice(0, 10),
    title: "Today's Institutional Buying",
    metaDescription: "Daily institutional buying activity highlights on MotiveFX.",
    kicker: "Daily intelligence",
    lead: "Block trades and accumulation patterns flagged against 30-day baselines.",
    sections: [{ heading: "Freshness", paragraphs: ["Published throughout the US session; archive builds SEO history over time."] }],
    faqs: [],
    relatedLinks: [{ label: "Institutional buying topic", href: "/topics/institutional-buying" }],
  },
  "options-activity": {
    slug: "options-activity",
    date: new Date().toISOString().slice(0, 10),
    title: "Today's Options Activity",
    metaDescription: "Unusual options activity daily digest on MotiveFX.",
    kicker: "Daily intelligence",
    lead: "Sweep and block summary with underlying linkage.",
    sections: [],
    faqs: [],
    relatedLinks: [{ label: "Options module", href: "/markets/options" }],
  },
  "crypto-intelligence": {
    slug: "crypto-intelligence",
    date: new Date().toISOString().slice(0, 10),
    title: "Today's Crypto Intelligence",
    metaDescription: "Daily crypto AI brief — BTC, ETH, and altcoin intelligence.",
    kicker: "Daily intelligence",
    lead: "24/7 market summary with funding and flow highlights.",
    sections: [],
    faqs: [],
    relatedLinks: [{ label: "Crypto module", href: "/markets/crypto" }],
  },
  "sports-intelligence": {
    slug: "sports-intelligence",
    date: new Date().toISOString().slice(0, 10),
    title: "Today's Sports Intelligence",
    metaDescription: "Daily sports betting analytics — line moves and sharp action.",
    kicker: "Daily intelligence",
    lead: "Line movement digest for major leagues.",
    sections: [],
    faqs: [],
    relatedLinks: [{ label: "Sports module", href: "/markets/sports" }],
  },
  "prediction-markets": {
    slug: "prediction-markets",
    date: new Date().toISOString().slice(0, 10),
    title: "Today's Prediction Markets",
    metaDescription: "Daily prediction market repricing and AI context.",
    kicker: "Daily intelligence",
    lead: "Probability shifts on major event contracts.",
    sections: [],
    faqs: [],
    relatedLinks: [{ label: "Predictions module", href: "/markets/predictions" }],
  },
};

export function getDaily(slug: string) {
  return DAILY_PAGES[slug];
}

export function allDailySlugs() {
  return Object.keys(DAILY_PAGES);
}
