import { useCallback, useEffect, useMemo, useState } from "react";
import { BellRing, ChevronDown, ChevronUp, History, Plus, RefreshCw, RotateCcw, Trash2 } from "lucide-react";
import type { HomeBriefing, IntelAlert } from "../types";
import { apiGet, apiPut } from "../lib/api";
import { useIntelAlerts } from "../hooks/useIntelAlerts";

type ReplayEvidence={provider:string;group:string;observedAt:string|null;confidence:number|null};
type ReplayOutcome={id:string;claim:string;horizonDays:number;predictedScore:number|null;predictedConf:number|null;entryPrice:number|null;outcomePrice:number|null;realizedReturnPct:number|null;evaluatorVersion:string;outcome:string;evaluatedAt:string|null;notes:string|null};
type ReplayPoint={motiveSignal:number|null;confidence:number|null;stance:string|null;recordedAt:string;engineVersion:string;evidence:ReplayEvidence[];outcomes:ReplayOutcome[]};
type ReplayItem={symbol:string;currentSignal:number|null;previousSignal:number|null;delta:number|null;confidence:number|null;stance:string|null;engineVersion:string|null;recordedAt:string|null;evidence:ReplayEvidence[];latestOutcome:(ReplayOutcome&{snapshotAt:string})|null;history:ReplayPoint[]};
type TrackRecordData={generatedAt:string;snapshotCount:number;pendingOutcomes:number;resolvedOutcomes:number;minimumResolvedForScore:number;readiness:"READY"|"COLLECTING_OUTCOMES";score:number|null;note:string;calibration:{evaluatorVersion:string;evaluated:number;forecastReady:boolean;buckets:Array<{bucket:string;predictedMin:number;predictedMax:number;sampleSize:number;observedReliability:number|null;warning:boolean;calibrationReady:boolean}>};recentOutcomes:Array<ReplayOutcome&{symbol:string;snapshotAt:string}>;replay:ReplayItem[]};
type Agent=NonNullable<HomeBriefing["watchAgents"]>[number];

export function MotiveTrackRecord(){
  const [data,setData]=useState<TrackRecordData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[expanded,setExpanded]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{setData(await apiGet<TrackRecordData>("/intel/track-record"));}catch(e){setError(e instanceof Error?e.message:"Track Record unavailable.");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load()},[load]);
  return <section className="v2-section v2-trust-section" id="v2-track-record">
    <header className="v2-section-head"><div><span className="v2-eyebrow">TRUST LAYER</span><h2><History size={18}/> Motive Track Record & Replay</h2></div><button type="button" onClick={()=>void load()} disabled={loading}><RefreshCw size={14}/> Refresh</button></header>
    {error?<p className="v2-warmup" role="alert">{error}</p>:!data?<p className="loading">Loading recorded signal history…</p>:<>
      <div className="v2-trust-kpis"><div><span>Recorded snapshots</span><strong>{data.snapshotCount.toLocaleString()}</strong></div><div><span>Resolved outcomes</span><strong>{data.resolvedOutcomes.toLocaleString()}</strong></div><div><span>Pending outcomes</span><strong>{data.pendingOutcomes.toLocaleString()}</strong></div><div><span>Historical reliability</span><strong>{data.score==null?"Collecting":data.score+"%"}</strong></div></div>
      <p className="v2-trust-note">{data.note}</p>
      {(data.calibration?.evaluated??0)>0&&<div className="v2-calibration"><h3>Calibration by evidence-confidence bucket</h3><div>{(data.calibration?.buckets??[]).map((b)=><span key={b.bucket} className={b.warning?"is-warning":""}><b>{b.bucket}</b><em>{b.sampleSize} samples</em><strong>{b.observedReliability==null?"—":b.observedReliability+"%"}</strong></span>)}</div><p>{data.calibration?.forecastReady?"Calibration has enough resolved history for supported forecast views.":"Forecast probability stays unavailable until resolved-history readiness is met."}</p></div>}
      <div className="v2-replay-head"><RotateCcw size={16}/><div><strong>Signal Replay</strong><span>Open a symbol to see what Motive recorded then, the evidence available at that time, how the signal changed, and any resolved outcome.</span></div></div>
      <div className="v2-replay-grid">{data.replay.slice(0,12).map((row)=><article key={row.symbol} className="v2-replay-card">
        <button type="button" className="v2-replay-toggle" onClick={()=>setExpanded(expanded===row.symbol?null:row.symbol)} aria-expanded={expanded===row.symbol}>
          <div className="v2-replay-top"><strong>{row.symbol}</strong><span>{row.recordedAt?new Date(row.recordedAt).toLocaleString():"—"}</span></div>
          <div className="v2-replay-signal"><span>Motive Signal</span><b>{row.currentSignal!=null?Math.round(row.currentSignal):"—"}</b><em>/100</em></div>
          <p>{row.delta==null?"No prior snapshot in this replay window.":(row.delta>=0?"+":"")+row.delta+" points vs prior recorded snapshot."}</p>
          <small>{row.stance?"Model view: "+row.stance.replace(/_/g," "):"Stance unavailable"}{row.confidence!=null?" · evidence confidence "+Math.round(row.confidence)+"/100":""}</small>
          <span className="v2-replay-expand">{expanded===row.symbol?<ChevronUp size={15}/>:<ChevronDown size={15}/>} {expanded===row.symbol?"Hide timeline":"Open timeline"}</span>
        </button>
        {expanded===row.symbol&&<div className="v2-replay-timeline">{row.history.map((point,i)=><div key={point.recordedAt+i}><time>{new Date(point.recordedAt).toLocaleString()}</time><strong>Motive Signal {point.motiveSignal==null?"—":Math.round(point.motiveSignal)}/100</strong><span>{point.confidence!=null?"Evidence confidence "+Math.round(point.confidence)+"/100":"Evidence confidence unavailable"}</span>{point.evidence.length>0&&<ul>{point.evidence.map((ev,j)=><li key={j}>{ev.provider} · {ev.group.replace(/_/g," ").toLowerCase()}</li>)}</ul>}{point.outcomes.length>0&&point.outcomes.map((o)=><p key={o.id} className="v2-replay-outcome">Outcome: <b>{o.outcome}</b>{o.realizedReturnPct!=null?" · "+o.realizedReturnPct.toFixed(2)+"% observed return":""} · {o.horizonDays}d horizon</p>)}</div>)}</div>}
      </article>)}</div>
      {(data.recentOutcomes??[]).length>0&&<><h3 className="v2-subhead">Recently resolved outcomes</h3><div className="v2-outcome-list">{(data.recentOutcomes??[]).slice(0,8).map((o)=><div key={o.id}><strong>{o.symbol}</strong><span>{o.outcome}</span><span>{o.horizonDays}d</span><span>{o.realizedReturnPct==null?"—":o.realizedReturnPct.toFixed(2)+"%"}</span></div>)}</div></>}
    </>}
  </section>;
}

export function MotiveWatchAgents({briefing,onPrefsChanged}:{briefing:HomeBriefing;onPrefsChanged?:()=>void}){
  const {alerts}=useIntelAlerts();
  const [busy,setBusy]=useState<string|null>(null),[creating,setCreating]=useState(false);
  const [label,setLabel]=useState(""),[metric,setMetric]=useState<Agent["metric"]>("motive_signal"),[operator,setOperator]=useState<Agent["operator"]>("above"),[threshold,setThreshold]=useState(70),[targetType,setTargetType]=useState<Agent["targetType"]>("any"),[target,setTarget]=useState("");
  const builtIn=briefing.alertRules??[],themes=briefing.themeWatchlist??[],agents=briefing.watchAgents??[];
  const triggers=useMemo(()=>alerts.filter((a:IntelAlert)=>a.title.startsWith("Watch Agent:")).slice(0,8),[alerts]);
  async function persist(nextAgents:Agent[]){await apiPut("/intel/prefs",{prefs:{themeWatchlist:themes,alertRules:builtIn,watchAgents:nextAgents}});window.dispatchEvent(new Event("motivefx:alerts-refresh"));onPrefsChanged?.();}
  async function toggleBuiltIn(id:string){setBusy(id);try{await apiPut("/intel/prefs",{prefs:{themeWatchlist:themes,alertRules:builtIn.map((r)=>r.id===id?{...r,enabled:!r.enabled}:r),watchAgents:agents}});window.dispatchEvent(new Event("motivefx:alerts-refresh"));onPrefsChanged?.();}finally{setBusy(null)}}
  async function toggle(id:string){setBusy(id);try{await persist(agents.map((a)=>a.id===id?{...a,enabled:!a.enabled}:a));}finally{setBusy(null)}}
  async function remove(id:string){setBusy(id);try{await persist(agents.filter((a)=>a.id!==id));}finally{setBusy(null)}}
  async function add(){const clean=label.trim()||"Custom Watch Agent";const next:Agent={id:"agent-"+Date.now(),label:clean.slice(0,120),metric,operator,threshold:Math.max(0,Math.min(100,threshold)),targetType,target:targetType==="any"?undefined:target.trim().slice(0,160),windowHours:24,enabled:true,createdAt:new Date().toISOString(),delivery:"intel_alert"};setBusy(next.id);try{await persist([...agents,next]);setCreating(false);setLabel("");setTarget("");}finally{setBusy(null)}}
  return <section className="v2-section v2-trust-section" id="v2-watch-agents">
    <header className="v2-section-head"><div><span className="v2-eyebrow">WATCH AGENTS</span><h2><BellRing size={18}/> Motive Watch</h2></div><button type="button" onClick={()=>setCreating((v)=>!v)}><Plus size={14}/> New Agent</button></header>
    <div className="v2-trust-kpis"><div><span>Active agents</span><strong>{agents.filter((a)=>a.enabled).length+builtIn.filter((r)=>r.enabled).length}</strong></div><div><span>Custom agents</span><strong>{agents.length}</strong></div><div><span>Built-in rules</span><strong>{builtIn.length}</strong></div><div><span>Recent triggers</span><strong>{triggers.length}</strong></div></div>
    <p className="v2-trust-note">Create persistent evidence watches across symbols, themes and markets. Agents write Intel Alerts only. They never place orders, purchases, trades or wagers.</p>
    {creating&&<div className="v2-agent-builder"><label>Name<input value={label} onChange={(e)=>setLabel(e.target.value)} placeholder="BTC evidence watch"/></label><label>Metric<select value={metric} onChange={(e)=>setMetric(e.target.value as Agent["metric"])}><option value="motive_signal">Motive Signal</option><option value="signal_change">Signal change</option><option value="evidence_confidence">Evidence confidence</option><option value="divergence">Consensus divergence</option></select></label><label>Condition<select value={operator} onChange={(e)=>setOperator(e.target.value as Agent["operator"])}><option value="above">At or above</option><option value="below">At or below</option><option value="changes_by">Changes by</option></select></label><label>Threshold<input type="number" min="0" max="100" value={threshold} onChange={(e)=>setThreshold(Number(e.target.value))}/></label><label>Target<select value={targetType} onChange={(e)=>setTargetType(e.target.value as Agent["targetType"])}><option value="any">Any</option><option value="symbol">Symbol</option><option value="theme">Theme</option><option value="module">Market desk</option></select></label>{targetType!=="any"&&<label>Target value<input value={target} onChange={(e)=>setTarget(e.target.value)} placeholder={targetType==="symbol"?"BTC":targetType==="module"?"crypto":"Oil and inflation"}/></label>}<button type="button" className="btn v2-primary" disabled={busy!=null||(targetType!=="any"&&!target.trim())} onClick={()=>void add()}>Create Watch Agent</button></div>}
    <ul className="v2-agent-list">{agents.length?agents.map((agent)=><li key={agent.id}><div><strong>{agent.label}</strong><span>{agent.metric.replace(/_/g," ")} · {agent.operator.replace(/_/g," ")} {agent.threshold}{agent.target?" · "+agent.target:""} · {agent.enabled?"watching":"paused"}</span></div><div className="v2-agent-actions"><button type="button" className="btn btn-sm btn-ghost" disabled={busy===agent.id} onClick={()=>void toggle(agent.id)}>{agent.enabled?"Pause":"Start"}</button><button type="button" className="btn-icon btn-icon-danger" aria-label={"Delete "+agent.label} disabled={busy===agent.id} onClick={()=>void remove(agent.id)}><Trash2 size={14}/></button></div></li>):<li><div><strong>No custom agents yet</strong><span>Create one from evidence, signal change, confidence, or divergence.</span></div></li>}</ul>
    {triggers.length>0&&<><h3 className="v2-subhead">Recent agent triggers</h3><ul className="v2-agent-trigger-list">{triggers.map((alert)=><li key={alert.id}><strong>{alert.title}</strong><span>{alert.body??"Rule matched recorded evidence."}</span><time>{new Date(alert.createdAt).toLocaleString()}</time></li>)}</ul></>}
    {builtIn.length>0&&<details className="v2-built-in-rules" open={!agents.length}><summary>Built-in predictive rules ({builtIn.length})</summary><ul className="v2-agent-list">{builtIn.map((r)=><li key={r.id}><div><strong>{r.label??r.kind}</strong><span>threshold {r.threshold} · {r.enabled?"watching":"paused"}</span></div><button type="button" className="btn btn-sm btn-ghost" disabled={busy===r.id} onClick={()=>void toggleBuiltIn(r.id)}>{r.enabled?"Pause":"Start"}</button></li>)}</ul></details>}
  </section>;
}
